spring:
  datasource:
    username: root
    password: mysql@123!
    url: jdbc:mysql://localhost:3306/hibdemo
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
logging:
  level:
    org.springframework.orm.jpa.JpaTransactionManager: debug
